#!/bin/bash
#
#       /etc/init.d/sqs-listener
#
#       This SQS Listener polls amazon aws for provisioning commands.
#

# Source function library.
. /etc/init.d/functions

# Default options
BANG_DISPATCHER_PATH="bang-dispatcher" # Override this to change which executable to run.
BANG_DISPATCHER_NAME="bang-dispatcher"

# User-specified variables
. /etc/default/bang-dispatcher

CONFIG_PATH="~$RUN_AS_USER/.sqslistener"

if [ -z RUN_AS_USER ]; then
	RUN_AS_USER='root'
fi

if [ -z $BANG_DISPATCHER_NAME -o -z $BANG_DISPATCHER_PATH ]; then
	>&2 echo "Error: BANG_DISPATCHER_NAME and BANG_DISPATCHER_PATH variables cannot be empty."
        exit 1
fi

start() {
   	pgrep $BANG_DISPATCHER_NAME &> /dev/null
	running=$?

	if [ $running -ne 0 ]; then
		echo -n "Starting sqs-listener: "
      		daemon $BANG_DISPATCHER_PATH $CONFIG_PATH --user $RUN_AS_USER &> /home/bang-dispatcher/sqslistener/logs/debug.log &
       		RET=$?
       		return $RET
	else
		echo "Sqs-listener is already running."
		return 0
	fi
}

stop() {

    echo -n "Shutting down sqs-listener: "
    killproc $BANG_DISPATCHER_PATH
    RET=$?
    return $RET
}

check_status() {
    status $BANG_DISPATCHER_PATH
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        check_status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: sqs-listener {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?